[project]
name = "Pearl-Calculator"
version = "0.1.0"
description = "A pearl calculator"
requires-python = "==3.12.10"
dependencies = [
    "torch==2.8.0",
    "numpy<2",
    "tqdm>=4.67.1",
]

[dependency-groups]
dev = [
    "ruff>=0.14.13",
]
